### DISCUSSION TITLE
E8450 云编译出错

### DISCUSSION THREAD

**Discussion by ericvwv** [Boos4721/openwrt#61] [Bugs/问题反馈]
详见 https://github.com/ericvwv/Redmi_AX6/runs/4806315824

**Comment by Boos4721** [comment]
alreday dropd this device.

**Reply by ericvwv** [reply]
=,= nice.

**Reply by Deleted-Account** [reply]
> alreday dropd this device.

so you dropped support of AX6 as well?

github action's compilation kept failed after Jan 20th

**Reply by Boos4721** [reply]
> > alreday dropd this device.
> 
> so you dropped support of AX6 as well?
> 
> github action's compilation kept failed after Jan 20th

only mtk

**Comment by Deleted-Account** [comment]
Despite I minimized the config file to only three lines:
```
CONFIG_TARGET_ipq807x=y
CONFIG_TARGET_ipq807x_generic=y
CONFIG_TARGET_ipq807x_generic_DEVICE_redmi_ax6=y
```

and also commented out diy-part1 and 2 .sh in workflow env:
```
env:
  REPO_URL: https://github.com/Boos4721/openwrt
#  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
#  CONFIG_FILE: .config
  CONFIG_FILE: AX6.config
#  DIY_P1_SH: diy-part1.sh
#  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  FILE_NAME: OpenWRT-Redmi~AX6
```

github action compilation for AX6 kept failed after Jan 19th like this:

```
Run cd openwrt/bin/targets/*/*
/home/runner/work/_temp/dfaa8fce-038b-47a9-85c0-7ce0ac63dbf1.sh: line 1: cd: openwrt/bin/targets/*/*: No such file or directory
Error: Process completed with exit code 1.
```

if I switch repo to Lean's, everything works.

: (
